import Head from "next/head";
import { MongoClient } from "mongodb";
import { Post } from "../components/posts/Post";

export default function Home({ result }) {
  return (
    <div className="container">
      <Head>
        <title>Next-Bootstrap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Post result={result} />
    </div>
  );
}

// export async function getStaticProps() {
//   const response = await fetch(
//     "https://jsonplaceholder.typicode.com/posts?_limit=10"
//   );
//   const data = await response.json();
//   console.log(data);

//   return {
//     props: {
//       data,
//     },
//   };
// }

export const getServerSideProps = async () => {
  const client = await MongoClient.connect(
    "mongodb+srv://meche:meche.in@cluster0.j9fvny4.mongodb.net/?retryWrites=true&w=majority"
  );
  console.log(client);
  const db = client.db();
  const record = db.collection("books");
  const results = await record.find().toArray();
  console.log(results);
  client.close();

  return {
    props: {
      result: results.map((item) => ({
        title: item.title,
        author: item.author,
        date: item.date,
        id: item._id.toString(),
        description: item.description,
      })),
      // revalidate: 1,
    },
  };
};
